alias bcat='bcatcat --theme=ansi'
alias cp='cp -iv'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gdb='gdb -q'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias mv='mv -iv'
alias rm='rm -iv'
alias babbage='ssh -Y tbitangimana@babbage.cs.tcu.edu'